url: https://www.lab21apps.com.br
baseurl: /lab21apps/

# Site settings
title: Lab21Apps
email: lab21apps@gmail.com
description: "Website desenvolvido para a startup Lab21Apps. A Lab21Apps é uma startup voltada para desenvolvimendo de aplicativos e websites"


# Team names, titles and social links
people:
- name: Sergio Mendoça
  pic: 1
  position: Diretor
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Giovane Ferreira
  pic: 2
  position: Desenvolvedor
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Alvanir Júnior
  pic: 3
  position: Desenvolvedor
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Victor Souto
  pic: 4
  position: Desenvolvedor
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty